
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: $walletdb
      POSTGRES_USER: $yourusername
      POSTGRES_PASSWORD: $yourpassword
    ports:
      - "5422:5422"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallet-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5422/walletdb
      SPRING_DATASOURCE_USERNAME: $yourusername
      SPRING_DATASOURCE_PASSWORD: $yourpassword
    depends_on:
      - postgres

volumes:
  postgres_data:
