spring:
  datasource:
    url: jdbc:postgresql://localhost:5422/walletdb
    username: $username
    password: $password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.